export { default as BotaoCadastrar } from "./BotaoCadastrar";
export { default as Cabecalho } from "./Cabecalho";
export { default as BarraDeBusca } from "./BarraDeBusca";
export { default as Pagina } from "./Pagina";
export { default as Listagem } from "./Listagem";
export { default as Titulo } from "./Titulo";
export { default as BotaoInfo } from "./BotaoInfo";
export { default as ModalRemover } from "./ModalRemover";
export { default as BotaoAlterar } from "./BotaoAlterar";
